### ISSUE TITLE
UUID v4 Support

### ISSUE THREAD

**Issue by yfuruyama** [cloudspannerecosystem/gcsb#1]
## Basic Idea
Supports UUID v4 data generation.

### Infer UUID v4 by default
Google [recommends](https://cloud.google.com/spanner/docs/schema-design#uuid_primary_key) using UUID v4 for primary keys in Cloud Spanner and it has been widely adopted as a best practice.

Hence, it might make sense to infer if a certain column is supposed to have UUID v4 and if looks so, automatically generates UUID v4 value for the column. This inference would make it easy to load data without forcing users to write the configurations.

### How to infer UUID v4
There are several ways for users to store UUID v4 value. For instances,

- In a `STRING(36)` column (e.g. `"f13c1af5-07cd-4db6-8891-ffa4acbd4991"`).
- In a `STRING(32)` column without `-` (e.g. `"f13c1af507cd4db68891ffa4acbd4991"`)
- In a `BYTES(16)` column (e.g. `<BYTE_ARRAY>`).

Among them I guess most users would choose `STRING(36)` for UUID v4, so we can only infer that if the column type is exactly `STRING(36)`.

### GCSB Configuration
We can provide an explicit way to use the UUID v4 generation through the config. This is an example of the config for UUID v4 support.

```yaml
# gcsb.yaml
tables:
- name: User
  columns:
  - name: UserId
    generator:
      type: UUID_V4
```

Currently there is a field called `type` in `generator` field. For this purpose we can create a new value for the `type` field: `UUID_V4`.

(Question: Can we use that field to specify the actual data type? Or should we treat it as a Spanner data type like STRING and define a new field like `sub_type` for `UUID_V4`?)

This `UUID_V4` is only valid if the column type is either of the following.

- `STRING(36)`
- `STRING(32)`
- `BYTES(16)`

The actual data generated by this tool will vary depending on the column type. For example, if the column type is `STRING(32)`, we generate `f13c1af507cd4db68891ffa4acbd4991` for the value. If the column type is not in the above list, we should report an error explicitly.

### Other Details
- This design only focuses on UUID v4. In other words, we will treat each UUID version differently. If users would like to use UUID v1, we can think of adding `UUID_V1` type afterward.

**Comment by snehashah16** [comment]
This design looks fine to me, I will let one of our customers chime in.

**Comment by yfuruyama** [comment]
Now this is merged into the master branch.
