### ISSUE TITLE
gcsb

### ISSUE THREAD

**Issue by mohammadsinan** [cloudspannerecosystem/gcsb#7]
HI,
How to download and use this tool

**Comment by yfuruyama** [comment]
Hi,

Please [install Go](https://go.dev/doc/install) and run the following command to install gcsb.

```
go install github.com/cloudspannerecosystem/gcsb@latest
```

**Comment by matthewjumpsoffbuildings** [comment]
@yfuruyama how about adding some install/run instructions to the docs?
